FROM registry.access.redhat.com/ubi10/ubi

RUN dnf -y install python3-pip && dnf clean all

RUN groupadd -r -g 1005 appgroup && \
    useradd -r -u 1005 -g 1005 -d /app -s /sbin/nologin -c "Application User" appuser
WORKDIR /app
COPY --chown=appuser:appgroup /app .

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
RUN python3 -m pip install --no-cache-dir -r requirements.txt

USER appuser
EXPOSE 5000
CMD ["python3", "app.py"]
