FROM python:3.12-slim

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt 

RUN useradd -m -u 1000 appuser && \
    chown -R appuser:appuser /app
USER appuser
COPY app .

EXPOSE 5000
CMD ["python", "app.py"]
