FROM quay.io/hummingbird/python:3.12

USER 0
RUN [ "python3", "-m", "venv", "/opt/venv" ]
ENV PATH="/opt/venv/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

WORKDIR /app
COPY app/requirements.txt .
RUN --mount=type=secret,id=pip.conf,target=/opt/venv/pip.conf [ "pip3", "install", "--no-cache-dir", "-r", "requirements.txt" ]

USER ${CONTAINER_DEFAULT_USER}
COPY app .

EXPOSE 5000
CMD ["python3", "app.py"]
